### ISSUE TITLE
Parsing of existing Change Log file

### ISSUE THREAD

**Issue by skywinder** [skywinder/github-changelog-generator#212]
This is sub-task of #209.

As @estahn mention:

The `CHANGELOG.md` needs to be parsed and divided into sections which represent the versions, e.g. 
```ruby
    [{ :version => 'v0.0.1', :content => '...' }, { :version => 'v1.0.0', :content => '...' }, ...]
```

It's needed to implement:
- `--amend` #211
- `Ability to keep manual added information for older version tags` #213

**Comment by estahn** [comment]
@skywinder I changed the parser to allow any kind of version number. Also added a bunch of rspec tests and rubocop to check for validity.

Travis is currently failing because most of the files are not compliant with rubocop. You could just run `rubocop --auto-correct <filename>` to fix the issues automatically.

Thoughts?
