### ISSUE TITLE
Squash Release Candidates into the Release

### ISSUE THREAD

**Issue by tjsail33** [skywinder/github-changelog-generator#309]
It would be great if there was an option to squash the 1.0.0-rc.0 and 1.0.0-rc.1 and so on tags into one larger 1.0.0 section of the changelog.

**Comment by ryanramadhan** [comment]
wow, great started

**Comment by skywinder** [comment]
Yes, I also thought about this. But there is no clear behaviour, in which case should we delete postfix, and in which cases not.
So, I decide to not implement such a hard logic, since there 2 good workaround for that case:

1. remove rc tags from repo. (destructive way)
2. Use `--exclude-tags` option  to specify which tags should excluded. (thanks, to @olleolleolle - and #281 PR - now you can do that easily with regex pattern, according your tags style!)

**Comment by tjsail33** [comment]
@skywinder would you welcome a PR that included this functionality should I have time to work on it?

**Comment by skywinder** [comment]
@tjsail33 
- Yes, I can review this PR, but I it should be covered by tests
- Please, make this feature not disabled by default, i.e. user have to specify additional key for this feature.

**Comment by crucialfelix** [comment]
It looks like if you exclude a tag then the features and fixes it contained simply disappear from the timeline. They do not get merged with the following tag as I would expect.

That means if we exclude release candidates then the final release has no changes listed at all.  We do not want to delete those tags, those were actual beta and alpha releases.

**Comment by skywinder** [comment]
@crucialfelix excluded tags shouldn't affect issues. the issues will listed under next release as if that tag doesn't exists.

**Comment by crucialfelix** [comment]
okay, today I did get that to work. you are correct, it does work. thanks

**Comment by skywinder** [comment]
@crucialfelix :+1:  you are welcome!
@tjsail33 Feel free to reopen this question, if you still have any questions.
