### ISSUE TITLE
Can we exclude closed Requests

### ISSUE THREAD

**Issue by liuxuan30** [skywinder/github-changelog-generator#632]
Hi there,

We have been using this for a long time. But our changelog.md keeps going, and I found many of them are closed issues, which we don't want to include:https://github.com/danielgindi/Charts/blob/master/CHANGELOG.md

I checked the -h options, there are no one to exclude closed issues. Is there anyway to simplify the change log?

**Comment by olleolleolle** [comment]
@liuxuan30 One of the ways is to create a GitHub Label, and tag the closed issue with _that label_ in order to exclude it from the generated changelog. The tool has such an option (in a newer release, _perhaps_ even only on `master` - if you can use a `Gemfile` and specifically install the `master` version from git, you'll be using latest):

```
--exclude-labels x,y,z

Issues with the specified labels will be always excluded from changelog. Default is 'duplicate,question,invalid,wontfix'
```

**Comment by liuxuan30** [comment]
ah, @olleolleolle Thanks for the information!

**Comment by liuxuan30** [comment]
@olleolleolle sorry to ask, is this default lags a feature of 1.15 release? Seems it's still in beta so gem update won't work. Any idea when 1.15 will be released?

**Comment by olleolleolle** [comment]
Perhaps you can update with “gem install” with the long option `pre` (“minus minus pre”, I’m typing on a phone). `gem -h` could have information on this. I hope this helps.

**Comment by liuxuan30** [comment]
any idea when would 1.15 be released? almost a year 😂
